### ISSUE TITLE
Linting .c files

### ISSUE THREAD

**Issue by ghost** [secularbird/cpplint-extension#11]
The plugins lints .c files. I thought that cpplint was just a C++ linter.

Is there a way to specify the file extensions to be linted by the plugin?

**Comment by ghost** [comment]
Sorry for wasting your time, I've found the `cpplint.excludes` setting. 

I only wish to use cpplint for C++ and not C. The problem is that some C++ code uses .h for header files and others use .hpp.

How difficult would it be to run cpplint based on the language identifier? So as well as `cpplint.excludes` there could be a setting named `cpplint.languages` which is also an array of strings and cpplint only executes if the language identifier for the current file matches one of those strings.

for example, if:

```js
"cpplint.languages":  ["cpp"]
```
Then regardless of the file extension (except if `cpplint.excludes` is set) the plugin would try to lint the file if its language identifier was 'cpp'.

**Comment by secularbird** [comment]
I'll append cpplint:extensions， filter file extensions of cpp, c, cxx

**Comment by secularbird** [comment]
version 0.0.9 had append the extensions of files for filtering cpp and c files
