### ISSUE TITLE
Workspace analysys progress runs only once, lacks feedback

### ISSUE THREAD

**Issue by gp-alex** [secularbird/cpplint-extension#17]
Workspace Analysys runs silently, so it's hard to judge is plugin working at all.
For me, it seems to run only once after startup, if I immideately run cpplint.runWholeAnalysis (ctrl+shift+p) and let VS Code alone for few minutes.
After changes, any subsequent runs do nothing.

Also, isn't in intended to run continuously in the background?

My VS Code:

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by secularbird** [comment]
> Workspace Analysys runs silently, so it's hard to judge is plugin working at all.
For me, it seems to run only once after startup, if I immideately run cpplint.runWholeAnalysis (ctrl+shift+p) and let VS Code alone for few minutes.
After changes, any subsequent runs do nothing.
> Also, isn't in intended to run continuously in the background?

When save the document, the whole workspace scan will run, there should not be many files in the workspace, the whole scan will take a long time to finish.
And cpplint.runWholeAnalysis  is not the same as workspace mode.
