### ISSUE TITLE
Extension loading well but nothing happen

### ISSUE THREAD

**Issue by remigastaldi** [secularbird/cpplint-extension#19]
In console log i have the "Congratulations, your extension "cpplint" is now active!" but nothing happen in c++ files.

Config : Archlinux x64, VSCode 1.24, cpplint 0.1.1

**Comment by secularbird** [comment]
I need more detail information, like how did u setup cpplint in vscode settings, whether your cpplint works in a terminal

**Comment by remigastaldi** [comment]
I installed cpplint on my system with package manager so it's in /bin/cpplint, it works on terminal and Atom.
In the cpplint VSCode settings i changed the cpplintPath to /bin/cpplint, do i need to change other parameters ?

**Comment by secularbird** [comment]
Which cpplint did you installed?  https://github.com/google/styleguide ?

**Comment by remigastaldi** [comment]
I have the 456.r40-1 version installed, i tried to download the python script from the github and set the path parameter to it but i have the same issue

**Comment by secularbird** [comment]
I don't know where this version cpplint is coming from.

cpplint from https://github.com/google/styleguideis is not supported right now, please install cpplint from https://github.com/cpplint/cpplint or using pip to install cpplint.

**Comment by remigastaldi** [comment]
This is the archlinux version from official google github, anyway with the https://github.com/cpplint/cpplint it's working.
I guess the problem is --repository is unknow in the official one.
Thanks for your help.
