### ISSUE TITLE
Slowdown when modifying another extensions settings

### ISSUE THREAD

**Issue by Gruntfuggly** [secularbird/cpplint-extension#20]
I noticed that when I had a large .cpp file open (>8000 lines), it took 10 to 15 seconds for something to happen when clicking a button in one of my extensions. In the extension, the button causes the configuration to be changed. The event listener attached to onDidChangeConfiguration wasn't getting called for 10 to 15 seconds. I started disabling extensions and isolated it to cpplint.

It seems odd that something in cpplint is being triggered by the configuration file changing?

**Comment by secularbird** [comment]
When configure change, the cpplint will be triggered. I think maybe I could add a thread to avoid this problem.

**Comment by secularbird** [comment]
Fix have been published, u may have some check.

**Comment by Gruntfuggly** [comment]
Hi - I've just tried it, but it doesn't seem to have made any difference?

Actually, it's not quite as bad as it was, but it still takes several seconds and changing the configuration a few times in quick succession actually blocks the whole application for a while...
