### ISSUE TITLE
The message is showed on the OUTPUT panel,but not the PROBLEMS panel

### ISSUE THREAD

**Issue by lazytao** [secularbird/cpplint-extension#21]
it seems that this plugin can't automatically lint file, but when i use the ctrl shift p to lint file, those messages were presented at the OUTPUT PANEL，here is my setting file:
<img width="727" alt="default" src="https://user-images.githubusercontent.com/41514978/44003339-b9ccd286-9e83-11e8-8240-912b41d3e3cf.png">

`{
    "cpplint.lineLength": 160,
    "cpplint.cpplintPath": "D:\\Anaconda3\\Scripts\\cpplint.exe",
    "cpplint.filters": [
        "-whitespace/tab",
        "-whitespace/newline"
    ],
    "cpplint.lintMode": "single",
}`

**Comment by secularbird** [comment]
Where is your cpplint coming from?

**Comment by g-arjones** [comment]
Same here.. Seems like the problem matchers are not working as expected
