### ISSUE TITLE
cpplint with anaconda3

### ISSUE THREAD

**Issue by ghost** [secularbird/cpplint-extension#23]
Hello.

I have installed cpplint within Anaconda3 env. e.g. 
~/anaconda3$ source ativate root
~/anaconda3$ cpplint --help
/home/ubuntu/anaconda3/bin/cpplint

so do I need to activate "Anaconda3" environment to work with cpplint for vs code plugin?

**Comment by secularbird** [comment]
You can follow #16.
Add a wrapper for cpplint.
