### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anothel** [secularbird/cpplint-extension#30]
- Issue Type: `Performance`
- Extension Name: `cpplint`
- Extension Version: `0.1.3`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.39.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\dream\mine.cpplint-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by secularbird** [comment]
I think this is ok, cpplint will take cpu when parsing files
