### ISSUE TITLE
How do i get it to  fix all errors from linting automatically?

### ISSUE THREAD

**Issue by Harsharma2308** [secularbird/cpplint-extension#37]
I have a lot of whitespace errors, is there a way I can get those fixed automatically?

**Comment by jorgeacortes** [comment]
Take a look at clang-format, it can automatically format C/C++ based on preconfigured styles (i.e. Google) and you can customize then. There are also extensions to integrate clang-format at vscode. Cpplint doesn't support formatting.

**Comment by Harsharma2308** [comment]
Thanks will check that out. Closing this for now.
