### ISSUE TITLE
Support forum Multi-root workspaces

### ISSUE THREAD

**Issue by bertmelis** [secularbird/cpplint-extension#6]
Is support for the "new" Multi-root workspaces feature planned?

Now cpplint only checks my files when I've got only 1 folder in my workspace.

**Comment by secularbird** [comment]
Visual code does only support one workspace, and cpplint extension will check the whole workspace no matter how many folders under it when it is on workspace mode.

**Comment by bertmelis** [comment]
I've looked into this again and I was not completely right. Only the first opened folder is parsed by cclint. If I add a second folder -also containing cpp-files- these are not covered by cpplint.

**Comment by secularbird** [comment]
I didn't using the `add folder to workspace` function before, I will check wether it could be implemented

**Comment by secularbird** [comment]
I had added the multi root support in the version 0.0.7
