### ISSUE TITLE
Add the 'root' and 'repository' agruments to configuration

### ISSUE THREAD

**Issue by Bulmanator** [secularbird/cpplint-extension#7]
This extension works great, however I would like to be able to pass the --root argument to define where my header guards are supposed to start (otherwise the linter picks them up as being incorrect). Also the repository argument would be nice to be able to set as "${workspaceFolder}" or something in the case that version control is not being used.

**Comment by secularbird** [comment]
version 0.0.8  has updated, add these settings

**Comment by Bulmanator** [comment]
Thank you for adding these settings, however for some reason the root option does not seem to be working for me. It still asks me to append INCLUDE to the front of my header guards. This happens with both the default and cpplint.root=include.

**Comment by Bulmanator** [comment]
Never mind, you can ignore my last comment and I can now confirm that these options are working correctly. Thanks again for implementing them
